
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int TK_KeyC = 18;
  public static final int PR_Inverso = 11;
  public static final int TK_BrackC = 20;
  public static final int PR_Seno = 12;
  public static final int PR_Operacion = 2;
  public static final int TK_Colon = 22;
  public static final int TK_Num = 16;
  public static final int PR_Tangente = 14;
  public static final int TK_Comma = 21;
  public static final int PR_Resta = 6;
  public static final int PR_Multiplicacion = 7;
  public static final int PR_Division = 8;
  public static final int EOF = 0;
  public static final int PR_Potencia = 9;
  public static final int PR_Mod = 15;
  public static final int error = 1;
  public static final int TK_KeyO = 17;
  public static final int PR_Valor2 = 4;
  public static final int PR_Valor1 = 3;
  public static final int PR_Raiz = 10;
  public static final int PR_Coseno = 13;
  public static final int TK_BrackO = 19;
  public static final int PR_Suma = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_Operacion",
  "PR_Valor1",
  "PR_Valor2",
  "PR_Suma",
  "PR_Resta",
  "PR_Multiplicacion",
  "PR_Division",
  "PR_Potencia",
  "PR_Raiz",
  "PR_Inverso",
  "PR_Seno",
  "PR_Coseno",
  "PR_Tangente",
  "PR_Mod",
  "TK_Num",
  "TK_KeyO",
  "TK_KeyC",
  "TK_BrackO",
  "TK_BrackC",
  "TK_Comma",
  "TK_Colon"
  };
}

